modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
# The modid of the mod
modId="medieval_weapons" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Barrels 2012" #mandatory
logoFile="medieval_weapons.png" #optional
authors="EERussianguy" #optional
description='''
An addon for TFC.
'''
[[dependencies.medieval_weapons]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.medieval_weapons]] #optional
    modId="curios" #mandatory
    mandatory=true #mandatory
    versionRange="[0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.medieval_weapons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
